eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
  servlet:
    context-path: /
spring:

  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:dev}
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: calculator
          uri: http://localhost:8090
          predicates:
            - Path=/calculator/**
        - id: notes
          uri: http://localhost:8070
          predicates:
            - Path=/notes/**

management:
  tracing:
    sampling:
      probability: 1.0


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: gateway
        primaryName: gateway
      - url: /notes/v3/api-docs
        name: notes
        primaryName: notes
      - url: /calculator/v3/api-docs
        name: calculator
        primaryName: calculator

