eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8100
  servlet:
    context-path: /
spring:
#  liquibase:
#    change-log: classpath:/liquibase/liquibase-changeLog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8191/auth/realms/training-notebook-microservice-realm/protocol/openid-connect/certs
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/keycloak
    username: postgres
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8222/account


management:
  tracing:
    sampling:
      probability: 1.0

openapi:
  service:
    title: account-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8222 #api gateway url
springdoc:
  api-docs:
    path: /account/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /account/swagger-ui.html

