eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8110
  servlet:
    context-path: /
spring:
  liquibase:
    change-log: classpath:/liquibase/liquibase-changeLog.xml
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8191/auth/realms/training-notebook-microservice-realm/protocol/openid-connect/certs
  application:
    name: nutrition
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nutrition
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  tracing:
    sampling:
      probability: 1.0

openapi:
  service:
    title: nutrition-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8222 #api gateway url
springdoc:
  api-docs:
    path: /nutrition/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /nutrition/swagger-ui.html

