version: '3'

services:

  notes:
    build:
      context: ./notes
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - postgres
    networks:
      - mynetwork  # Używamy tej samej sieci dla serwisów


  postgres:
    image: postgres
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:  # Tworzymy własną sieć Docker, którą będą używać serwisy
