spring:
  application:
    name: nutrition
  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-3.5-turbo
  config:
    import: optional:configserver:http://localhost:8888


